medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost  # or docker host if needed
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public
      threads: 4